FROM php:7.1-fpm-alpine

# Install dependencies
RUN apk add --no-cache --update \
    libcurl \
    libpq \
    postgresql-dev \
    curl-dev \
    openssl-dev \
    bzip2-dev \
    libxml2-dev \
    libmcrypt-dev \
    php7-pear \
    php7-dev \
    autoconf \
    g++ \
    make

# Install PHP extensions
RUN docker-php-ext-install \
    mcrypt \
    pdo_pgsql \
    pdo_mysql \
    bcmath

# Clean up (Alpine-based, but no apt clean needed)
RUN rm -rf /var/cache/apk/*